title: Alberta RL folks
logo: /assets/img/logo.png
description: We were formerly employed by a certain AI lab based out of London.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: ''
collections:
  people:
    output: true
